### ISSUE TITLE
Navigation Stack doesn't work with WatchOS

### ISSUE THREAD

**Issue by pkrakow** [matteopuc/swiftui-navigation-stack#47]
I've recently added a WatchOS target to an existing project that I developed with the Navigation Stack framework, and the WatchOS portion of the build fails if I try to "import NavigationStack". I've built a simple stand-alone app that demonstrates the problem in a really simple project: https://github.com/pkrakow/watchOS-Framework-Test

**Comment by matteopuc** [comment]
Hi @pkrakow thanks for reporting this issue. There are two problems here, one is yours, one is mine 😄 

Your problem is that you forgot to add the navigation stack framework as a dependency for the watchkit extension. Basically:
![Screenshot 2021-04-01 at 16 07 57](https://user-images.githubusercontent.com/5569047/113314328-7e224d80-930c-11eb-94d4-9f40ff953add.png)
![Screenshot 2021-04-01 at 16 08 14](https://user-images.githubusercontent.com/5569047/113314348-84b0c500-930c-11eb-9ddd-c26fb8437b7e.png)

My problem is that I forgot to add the `watchKit` platform to the Package.swift (this is mandatory). I've just created a PR to fix this issue (https://github.com/matteopuc/swiftui-navigation-stack/pull/48), as soon as the PR is accepted and merged you'll be able to use the navigation stack on WatchOS. 
Again, Thanks.
Matteo

**Comment by matteopuc** [comment]
@pkrakow Done!

**Comment by pkrakow** [comment]
Works like a charm - thanks.
