### ISSUE TITLE
Swift Package Manager installation not working - XCode 13

### ISSUE THREAD

**Issue by MartinMajewski** [matteopuc/swiftui-navigation-stack#68]
With XCode 13 the installation of NavigationStack as an SPM dependency is not working.

This is what I get:
![Screenshot 2021-10-04 at 11 27 18](https://user-images.githubusercontent.com/2221289/135827303-b2672240-d5fc-4b29-a408-80d4e277528e.png)

**Comment by matteopuc** [comment]
Thanks for reporting the issue. I'll check it as soon as possible 👍

**Comment by matteopuc** [comment]
Ok, the problem is that you are trying to import a `Package collection`, but this repository is not a `Package collection`, it's just a `Package` (package collections are a new feature of Swift 5.5 https://swift.org/blog/package-collections/). To import the navigation stack you have to copy the related URL (https://github.com/matteopuc/swiftui-navigation-stack) in the search field on top right in the window:

<img width="1082" alt="Screenshot 2021-10-04 at 12 28 10" src="https://user-images.githubusercontent.com/5569047/135836021-d6f7fd8b-6449-4a3f-b305-cf51bb6231b9.png">

And the press enter. Let me know if it works for you, I've just tried and everything works as expected.

**Comment by matteopuc** [comment]
Yes, it's a good idea. Maybe even with a quick GIF that shows how to properly import the package. Thanks.
